---
- name: Deploy application on Kubernetes
  hosts: all
  gather_facts: false
  become: yes
  tasks:
    - name: Create deployment
      k8s:
        api_version: apps/v1
        kind: Deployment
        name: my-deployment-fcr-admin
        namespace: ordear
        definition:
          metadata:
            labels:
              app: fcr-admin
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: fcr-admin
            template:
              metadata:
                labels:
                  app: fcr-admin
              spec:
                containers:
                  - name: fcr-admin-test
                    image: riadhbellazreg/fcr-admin:fcr-admin-test
                    imagePullPolicy: Always
                    ports:
                      - containerPort: 3000
    - name: Create service
      k8s:
        api_version: v1
        kind: Service
        name: my-service-fcr-admin
        namespace: ordear
        definition:
          metadata:
            labels:
              app: fcr-admin
          spec:
            selector:
              app: fcr-admin
            ports:
              - protocol: TCP
                port: 3033
                targetPort: 3000
            type: LoadBalancer
